package src.common;

public enum VravHeader {

	HEADER_LOGON,
	HEADER_LOGON_RESP,
	HEADER_LOGOFF,
	HEADER_MESSAGE,
	HEADER_ADD_TEXT,
	HEADER_REMOVE_TEXT,
	HEADER_REPLACE_TEXT,
	HEADER_GET_ACTIVITIES
}
